// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code


using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mytest.Detatil {

  /// <summary>Holder for reflection information generated from test.proto</summary>
  public static partial class TestReflection {

    #region Descriptor
    /// <summary>File descriptor for test.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp0ZXN0LnByb3RvEgZNeXRlc3QaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3Rh",
            "bXAucHJvdG8i/QEKC1Rlc3RfUGVyc29uEgwKBG5hbWUYASABKAkSDQoFbGV2",
            "ZWwYAiABKAUSEgoKcHJvZmVzc2lvbhgDIAEoCRIrCgNhbGwYBCADKAsyHi5N",
            "eXRlc3QuVGVzdF9QZXJzb24uUGVyc29uX2FsbBItCglsYXN0X3RpbWUYBSAB",
            "KAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wGkEKClBlcnNvbl9hbGwS",
            "CwoDbnVtGAEgASgJEiYKBHR5cGUYAiABKA4yGC5NeXRlc3QuVGVzdF9QZXJz",
            "b24uYXJlYSIeCgRhcmVhEgYKAmNoEAASBgoCdXMQARIGCgJ1axACQhGqAg5N",
            "eXRlc3QuRGV0YXRpbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mytest.Detatil.Test_Person), global::Mytest.Detatil.Test_Person.Parser, new[]{ "Name", "Level", "Profession", "All", "LastTime" }, null, new[]{ typeof(global::Mytest.Detatil.Test_Person.Types.area) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Mytest.Detatil.Test_Person.Types.Person_all), global::Mytest.Detatil.Test_Person.Types.Person_all.Parser, new[]{ "Num", "Type" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Test_Person : pb::IMessage<Test_Person> {
    private static readonly pb::MessageParser<Test_Person> _parser = new pb::MessageParser<Test_Person>(() => new Test_Person());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Test_Person> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mytest.Detatil.TestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Test_Person() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Test_Person(Test_Person other) : this() {
      name_ = other.name_;
      level_ = other.level_;
      profession_ = other.profession_;
      all_ = other.all_.Clone();
      lastTime_ = other.lastTime_ != null ? other.lastTime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Test_Person Clone() {
      return new Test_Person(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "profession" field.</summary>
    public const int ProfessionFieldNumber = 3;
    private string profession_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Profession {
      get { return profession_; }
      set {
        profession_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "all" field.</summary>
    public const int AllFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Mytest.Detatil.Test_Person.Types.Person_all> _repeated_all_codec
        = pb::FieldCodec.ForMessage(34, global::Mytest.Detatil.Test_Person.Types.Person_all.Parser);
    private readonly pbc::RepeatedField<global::Mytest.Detatil.Test_Person.Types.Person_all> all_ = new pbc::RepeatedField<global::Mytest.Detatil.Test_Person.Types.Person_all>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Mytest.Detatil.Test_Person.Types.Person_all> All {
      get { return all_; }
    }

    /// <summary>Field number for the "last_time" field.</summary>
    public const int LastTimeFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastTime {
      get { return lastTime_; }
      set {
        lastTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Test_Person);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Test_Person other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Level != other.Level) return false;
      if (Profession != other.Profession) return false;
      if(!all_.Equals(other.all_)) return false;
      if (!object.Equals(LastTime, other.LastTime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Profession.Length != 0) hash ^= Profession.GetHashCode();
      hash ^= all_.GetHashCode();
      if (lastTime_ != null) hash ^= LastTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (Profession.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Profession);
      }
      all_.WriteTo(output, _repeated_all_codec);
      if (lastTime_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LastTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Profession.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Profession);
      }
      size += all_.CalculateSize(_repeated_all_codec);
      if (lastTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Test_Person other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Profession.Length != 0) {
        Profession = other.Profession;
      }
      all_.Add(other.all_);
      if (other.lastTime_ != null) {
        if (lastTime_ == null) {
          LastTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastTime.MergeFrom(other.LastTime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 26: {
            Profession = input.ReadString();
            break;
          }
          case 34: {
            all_.AddEntriesFrom(input, _repeated_all_codec);
            break;
          }
          case 42: {
            if (lastTime_ == null) {
              LastTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastTime);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Test_Person message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum area {
        [pbr::OriginalName("ch")] Ch = 0,
        [pbr::OriginalName("us")] Us = 1,
        [pbr::OriginalName("uk")] Uk = 2,
      }

      public sealed partial class Person_all : pb::IMessage<Person_all> {
        private static readonly pb::MessageParser<Person_all> _parser = new pb::MessageParser<Person_all>(() => new Person_all());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Person_all> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mytest.Detatil.Test_Person.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Person_all() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Person_all(Person_all other) : this() {
          num_ = other.num_;
          type_ = other.type_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Person_all Clone() {
          return new Person_all(this);
        }

        /// <summary>Field number for the "num" field.</summary>
        public const int NumFieldNumber = 1;
        private string num_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Num {
          get { return num_; }
          set {
            num_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 2;
        private global::Mytest.Detatil.Test_Person.Types.area type_ = global::Mytest.Detatil.Test_Person.Types.area.Ch;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Mytest.Detatil.Test_Person.Types.area Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Person_all);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Person_all other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Num != other.Num) return false;
          if (Type != other.Type) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Num.Length != 0) hash ^= Num.GetHashCode();
          if (Type != global::Mytest.Detatil.Test_Person.Types.area.Ch) hash ^= Type.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Num.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Num);
          }
          if (Type != global::Mytest.Detatil.Test_Person.Types.area.Ch) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Type);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Num.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Num);
          }
          if (Type != global::Mytest.Detatil.Test_Person.Types.area.Ch) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Person_all other) {
          if (other == null) {
            return;
          }
          if (other.Num.Length != 0) {
            Num = other.Num;
          }
          if (other.Type != global::Mytest.Detatil.Test_Person.Types.area.Ch) {
            Type = other.Type;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Num = input.ReadString();
                break;
              }
              case 16: {
                Type = (global::Mytest.Detatil.Test_Person.Types.area) input.ReadEnum();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
